### ISSUE TITLE
Compatibility btw examples & Browser extension

### ISSUE THREAD

**Issue by doanva84** [SideeX/example#1]
Dear all,

1. I installed [latest version of SideeX](https://github.com/SideeX/sideex/blob/master/SideeX_2.3.4.zip)  in Chrome 
2. I downloaded examples from this repository.
3. **Problem**: IMPOSSIBLE to import/open any examples under [all_example](https://github.com/SideeX/example/blob/main/example_testsuites/all_example.zip) to SideeX_2.3.4
    * I always meet this kind of message:
```
"clickAt.html" is of the format of an early version of Selenium IDE. 
    Some commands may not work. Do you still want to open it?
```

- And no commands would be accepted (empty suite)

4. **Consequence Problem**: In opposite, exported script from SideeX_2.3.4 Chrome extension is not compatible to sideex-webservice v3.5.4 (npm i -g @sideex/webservice )
5. Question: which browser extension is compatible to example scripts here ?

Thank you,

**Comment by tyler8812** [comment]
Hi doanva84,

all_example.zip is supported by **SideeX 3**. 
You can download from [here](https://sideex.io/download/).

Best Regards,
SideeX Team

**Comment by doanva84** [comment]
Thank you @tyler8812 
I followed your hints and my problem was resolved
